// Editorial documentation only. Replace this content independently of the homepage or market service.
export interface DocSection {
  id: string;
  title: string;
  paragraphs: string[];
  items?: string[];
  flow?: string[];
  statuses?: { label: "LIVE" | "SIMULATION" | "COMING SOON"; title: string; detail: string }[];
}
export interface DocPage { slug: string; label: string; title: string; subtitle: string; description: string; sections: DocSection[] }

export const docsPages: DocPage[] = [
  { slug: "", label: "Overview", title: "CHAOS", subtitle: "Protocol Documentation", description: "An experimental system built around instability, randomness and interconnected markets.", sections: [
    { id: "overview", title: "Overview", paragraphs: ["CHAOS is an experimental memecoin project inspired by chaos theory and the butterfly effect. It explores how instability and randomness might become explicit inputs to a protocol, rather than treating markets as predictable systems.", "Today, the project combines a read-only Solana market observatory with a separate local visual simulation. The future financial protocol is still a design concept. CHAOS does not predict prices, guarantee outcomes or measure mathematical market chaos."] },
    { id: "how-it-works", title: "How It Works", paragraphs: ["The proposed financial lifecycle connects observation, a threshold and random selection. The sequence below describes design intent; selection, distribution and protocol resets are not implemented."], flow: ["MARKET DATA", "CHAOS INDEX", "100%", "CHAOS EVENT", "RANDOM SELECTION", "DISTRIBUTION", "RESET"] },
    { id: "current-status", title: "Current Status", paragraphs: ["Implementation status is explicit. Real market observations and simulated events are different kinds of data."], statuses: [
      { label: "LIVE", title: "Read-only market data", detail: "Implemented DEX Screener scanner, configurable eligibility filters and experimental index API. Availability and history coverage depend on the running worker and provider; this is off-chain data, not a live financial protocol." },
      { label: "SIMULATION", title: "Demonstrations only", detail: "Local slider, fictional token selection and visual distribution/reset. Backend threshold events are also simulated and never select tokens or move funds." },
      { label: "COMING SOON", title: "Financial protocol", detail: "Solana program, treasury, verifiable randomness, real token selection, distributions and on-chain cycle transitions. No contract or wallet interaction is implemented." },
    ] },
  ] },
  { slug: "theory", label: "The Theory", title: "The Theory", subtitle: "Rules, uncertainty and sensitive dependence", description: "The science behind the metaphor. Complexity and randomness are not proof of mathematical chaos.", sections: [
    { id: "deterministic-systems", title: "Deterministic systems", paragraphs: ["A deterministic system evolves according to rules. Exactly the same initial state produces the same trajectory. Some nonlinear deterministic systems are chaotic: nearby starting states can diverge dramatically over time."] },
    { id: "initial-conditions", title: "Sensitivity to initial conditions", paragraphs: ["Measurements have finite precision. In a chaotic system, a small uncertainty in the initial state can grow until a long-term forecast becomes unreliable. The rules remain deterministic even when practical prediction becomes difficult."] },
    { id: "butterfly-effect", title: "The butterfly effect", paragraphs: ["The butterfly effect is a metaphor for sensitive dependence on initial conditions, not a promise that every small disturbance creates a large event. The Lorenz attractor illustrates how a small set of deterministic equations can produce intricate, aperiodic motion.", "CHAOS borrows this lens for its identity. Its experimental market index does not establish that markets satisfy the mathematical definition of chaos."] },
  ] },
  { slug: "chaos-index", label: "Chaos Index", title: "Chaos Index", subtitle: "An experimental instability metric", description: "A modular 0–100 score computed from the observed eligible token sample. Formula v1 is provisional.", sections: [
    { id: "components", title: "Components", paragraphs: ["The backend combines five normalized inputs. Each score is clamped to 0–100 and combined using configurable weights; unavailable inputs remain null."], items: ["Volatility: standard deviation of historical log price returns, scaled to a five-minute interval.", "Trading activity: average 24-hour transaction count divided by 1440, a transactions-per-minute proxy.", "Volume change: absolute change in rolling 24-hour volume between comparable scans.", "Liquidity change: absolute change in selected-pair USD liquidity between comparable scans.", "Price dispersion: standard deviation of one-hour price changes across eligible tokens."] },
    { id: "readiness", title: "Readiness and freshness", paragraphs: ["The default minimum pool size is two tokens. Volatility requires at least three comparable observations. A provisional score is marked warming up until every enabled component meets the configured coverage requirement.", "Provider failures mark degradation; aged observations become stale. Incomplete or degraded evaluations cannot emit threshold events. Missing data is never presented as a fabricated zero measurement."] },
    { id: "threshold", title: "The 100% threshold", paragraphs: ["A complete, healthy backend index reaching 100 records a simulated CHAOS_EVENT_TRIGGERED event. A persisted latch prevents repeat events while the score remains at 100 and rearms after a healthy reading below 100.", "The measured index is not artificially reset. Real financial triggers and cycle resets belong to a future blockchain program. This score is not a scientific measure of market chaos or a price forecast."] },
  ] },
  { slug: "chaos-pool", label: "Chaos Pool", title: "Chaos Pool", subtitle: "Eligibility defines a set of possibilities", description: "An observed sample of Solana tokens, not a recommendation or registered on-chain pool.", sections: [
    { id: "eligibility", title: "Initial eligibility", paragraphs: ["The first backend filter applies these configurable defaults. They are experimental project settings, not permanent protocol rules."], items: ["Solana tokens only.", "Reported market cap greater than $1,000,000.", "Selected-pair liquidity greater than $250,000.", "Selected-pair 24-hour volume greater than $100,000.", "Selected-pair age of at least 30 days."] },
    { id: "coverage", title: "Coverage and pair identity", paragraphs: ["Discovery uses DEX Screener profiles, boosts, rotating searches and optional configured mint addresses. These feeds do not cover every Solana token. One representative, highest-liquidity observed base-token pair supplies the metrics for each token.", "Pair creation time is an age proxy, not verified token creation time. Missing required fields fail eligibility; FDV is not substituted for market cap. A change in representative pair can affect eligibility and historical continuity."] },
    { id: "interpretation", title: "What membership means", paragraphs: ["Eligibility describes whether a token meets the current filter. It does not predict performance, establish safety or endorse a token. The financial protocol would need its own implemented pool rules before any real selection could occur."] },
  ] },
  { slug: "chaos-engine", label: "Chaos Engine", title: "Chaos Engine", subtitle: "Observation now. Financial mechanics later.", description: "The current backend evaluates market observations. The future Solana program would own financial transitions.", sections: [
    { id: "implemented", title: "Implemented observation", paragraphs: ["A standalone worker periodically discovers and refreshes tokens, applies eligibility filters, calculates the experimental index and persists snapshots. Read-only APIs expose those snapshots without launching provider scans from page requests."] },
    { id: "proposed-lifecycle", title: "Proposed lifecycle", paragraphs: ["The future design would connect the threshold to verifiable random selection and distribution. This is not an operating financial mechanism."], flow: ["OBSERVE", "ACCUMULATE", "CHAOS INDEX", "100%", "CHAOS EVENT", "RANDOM SELECTION", "DISTRIBUTION", "RESET", "NEW CYCLE"] },
    { id: "responsibility", title: "Execution responsibility", paragraphs: ["The frontend must only read and display state. It must never authorize real distributions. The future blockchain program would enforce triggering, randomness, selection, treasury accounting and cycle transitions. Those program rules are not implemented yet."] },
  ] },
  { slug: "chaos-events", label: "Chaos Events", title: "Chaos Events", subtitle: "A trace of a threshold, not a transfer", description: "Current event records are explicitly simulated. No financial outcome is fabricated.", sections: [
    { id: "backend-events", title: "Backend events", paragraphs: ["A complete, healthy index evaluation at 100 can record CHAOS_EVENT_TRIGGERED with simulated: true, an observation timestamp and eligible token count. Selected token, distribution amount and transaction reference remain null.", "The event latch persists across worker restarts. The website reads the event history from /api/events or the complete /api/chaos snapshot."] },
    { id: "local-demo", title: "Local demonstration", paragraphs: ["In Simulation Mode, reaching 100 plays a local sequence: event triggered, selecting a fictional token, selected token, visual distribution and reset to zero. It runs entirely in browser state and does not populate the backend ledger."] },
    { id: "future-records", title: "Future on-chain records", paragraphs: ["A future program could publish verifiable selection and distribution records. Transaction links and real amounts will only be shown when an implemented read source supplies actual records. No such financial events exist in the current implementation."] },
  ] },
  { slug: "tokenomics", label: "Tokenomics", title: "Tokenomics", subtitle: "Parameters not yet published", description: "A reserved documentation area for confirmed token and treasury economics.", sections: [
    { id: "unannounced", title: "Current status", paragraphs: ["Tokenomics have not been finalized or implemented here. This documentation does not announce a supply, mint address, allocation, fee, launch schedule or distribution percentage."] },
    { id: "future-specification", title: "Future specification", paragraphs: ["Replace this editorial placeholder with confirmed parameters and their implementation references when available."], items: ["Supply and issuance rules.", "Allocations and any vesting conditions.", "Treasury accumulation and accounting.", "Event distribution policy and cycle economics."] },
  ] },
  { slug: "security", label: "Security", title: "Security", subtitle: "Keep observation separate from execution", description: "Current boundaries and requirements for a future financial protocol. No audit is claimed.", sections: [
    { id: "read-only", title: "Read-only frontend", paragraphs: ["The live source interface only reads snapshots. It contains no trigger, signing, wallet or distribution methods. A frontend index reading of 100 is not authority to move funds. Local simulation randomness is cosmetic and unsuitable for financial selection."] },
    { id: "data-boundaries", title: "Data and service boundaries", paragraphs: ["Provider data is off-chain and may be incomplete, stale or incorrect. Provenance, freshness and coverage are displayed explicitly. Caching, request pacing, timeouts, bounded retries and provider cooldowns limit unnecessary requests.", "Scanner configuration and future API credentials remain server-side. The current persisted store and worker lock support a single host; multi-host deployment requires shared persistence and distributed coordination."] },
    { id: "future-review", title: "Future protocol review", paragraphs: ["Before real financial execution, the program design would need review of permissions, accounting, randomness, replay protection and failure handling. No smart contract or smart-contract audit is implemented or claimed by this website."] },
  ] },
  { slug: "roadmap", label: "Roadmap", title: "Roadmap", subtitle: "Implementation stages, not promises", description: "Current progress and proposed next steps. No release dates are announced.", sections: [
    { id: "implemented", title: "Implemented", paragraphs: ["The visual identity, narrative homepage, local simulation, market-data scanner, configurable pool filter, experimental index, read-only APIs and documentation routes are implemented. Runtime market availability still depends on the worker and provider."] },
    { id: "research", title: "Research and refinement", paragraphs: ["Next work can evaluate sample coverage, improve discovery, review index calibration and data quality, and evolve persistence and operational monitoring. The first index formula remains adjustable."] },
    { id: "future-protocol", title: "Future financial protocol", paragraphs: ["Solana program design, verifiable randomness, treasury rules, actual selection and distributions remain proposed work. Security review and implementation evidence must precede claims that those features are live.", "This roadmap is a direction for an experiment, not a commitment to dates, returns or completed financial functionality."] },
  ] },
];

export const docsNavigation = docsPages.map(({ slug, label }) => ({ href: slug ? `/docs/${slug}` : "/docs", label }));
export const getDocPage = (slug: string) => docsPages.find(page => page.slug === slug);
