import { ArrowDown, ArrowUpRight, Atom, CircleDot, FlaskConical, Radio } from "lucide-react";
import { EngineCarousel } from "./engine-carousel";
import { Badge, Reveal, SectionLabel } from "./ui";
import { projectConfig, type ChaosEvent, type PoolToken } from "@/lib/chaos-data";

export function Engine() {
  return <section className="engine-section" id="engine"><div className="container section"><Reveal><div className="section-heading"><SectionLabel number="02">THE MECHANISM</SectionLabel><Badge>COMING SOON</Badge></div><div className="split-heading"><h2>The Chaos <span className="serif">Engine.</span></h2><p className="body-copy">The experimental Chaos Index now reads observed market data. At 100%, the planned Chaos Engine would select an eligible Solana token through verifiable randomness and distribute a portion of accumulated treasury resources.</p></div><EngineCarousel /><div className="engine-notice"><FlaskConical size={16} /><p>Financial mechanism coming soon. The future blockchain program will trigger events and execute distributions. This website will only read and display state. Market observation is available; financial selection and distribution are not implemented.</p><span className="mono">STATUS: CONCEPT ONLY</span></div></Reveal></div></section>;
}

export function Events({ events }: { events: ChaosEvent[] }) {
  return <section className="section container" id="events"><Reveal><SectionLabel number="03">THE DISTURBANCES</SectionLabel><div className="split-heading"><h2>Chaos <span className="serif">events.</span></h2><p className="body-copy">Every event will leave a trace.<br />This is how future experiments could be recorded.</p></div><div className="events-grid">{events.map(event => <article className="event-card" key={event.id}><div className="event-card-top"><CircleDot size={20} strokeWidth={1.25} /><Badge>DEMO</Badge></div><h3>CHAOS EVENT <span>#{event.id}</span></h3><dl><div><dt>Selected token</dt><dd>{event.selectedToken}</dd></div><div><dt>Distribution</dt><dd>{event.distributionSol ?? "--"} SOL</dd></div><div><dt>Timestamp</dt><dd>{event.timestamp ?? "--"}</dd></div><div><dt>Transaction</dt><dd>{event.transaction ?? "--"}</dd></div></dl><div className="event-foot mono"><span className="hollow-dot" />AWAITING FIRST DISTURBANCE</div></article>)}</div><p className="demo-note mono">DEMONSTRATION DATA ONLY. NO EVENTS OR TRANSACTIONS HAVE TAKEN PLACE.</p></Reveal></section>;
}

export function Pool({ tokens }: { tokens: PoolToken[] }) {
  return <section className="section container pool-section" id="pool"><Reveal><div className="section-heading"><SectionLabel number="04">THE POSSIBILITIES</SectionLabel><Badge>DEMO POOL</Badge></div><div className="split-heading"><h2>The Chaos <span className="serif">Pool.</span></h2><p className="body-copy">A possible universe of eligible tokens.<br />One selection. A new chain of consequences.</p></div><div className="pool-table-wrap"><table className="pool-table"><caption className="sr-only">Fictional eligible tokens. All market capitalization, liquidity, and eligibility data are demo values.</caption><thead><tr><th scope="col">TOKEN / SPECIMEN</th><th scope="col">MARKET CAP</th><th scope="col">LIQUIDITY</th><th scope="col">SIMULATED STATUS</th><th scope="col"><span className="sr-only">Data type</span></th></tr></thead><tbody>{tokens.map((token, i) => <tr key={token.symbol}><th scope="row"><div className="token-cell"><span className="token-icon" style={{ color: token.color }}><Atom size={20} strokeWidth={1.25} /></span><div><span>{token.symbol}</span><small>{token.name}</small></div><span className="specimen mono">0{i + 1}</span></div></th><td>{token.marketCap}</td><td>{token.liquidity}</td><td><span className="eligible"><span className="hollow-dot" />{token.status}</span></td><td><span className="mono table-demo">DEMO</span></td></tr>)}</tbody></table></div><p className="demo-note mono">FICTIONAL TOKENS AND METRICS. ELIGIBILITY CRITERIA HAVE NOT BEEN FINALIZED.</p></Reveal></section>;
}

export function Participate() {
  return <section className="participate section" id="participate"><Reveal className="container"><div className="participate-eyebrow mono"><Radio size={16} /> THE NEXT DISTURBANCE STARTS WITH YOU.</div><h2>YOU ARE NOT WATCHING<br />THE EXPERIMENT.<br /><span>YOU ARE PART OF IT.</span></h2><p>Follow the signal. Observe the evolution.<br />See what a small change can set in motion.</p><div className="participate-actions">{projectConfig.socialUrl ? <a className="button primary" href={projectConfig.socialUrl} target="_blank" rel="noopener noreferrer">Follow CHAOS <ArrowUpRight size={17} /></a> : <span className="social-placeholder"><Radio size={16} /> CA coming soon</span>}{projectConfig.communityUrl && <a className="button secondary" href={projectConfig.communityUrl} target="_blank" rel="noopener noreferrer">Join the community <ArrowUpRight size={16} /></a>}<a className="text-button" href="#engine">Explore what comes next <ArrowDown size={15} /></a></div><p className="prototype-note mono">EXPERIMENTAL MARKET DATA · SIMULATED EVENTS · NO BLOCKCHAIN TRANSACTIONS</p></Reveal></section>;
}
